# Generated by Django 4.2.4 on 2023-09-06 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('TECH', 'Technology'), ('FOOD', 'Food'), ('TRAV', 'Traveling'), ('PET', 'Pet Food'), ('TEST', 'Testing')], default=None, max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=120)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
